[[general]]
name = "dev"
excludeFiles = []
excludeDirectories = [".target/"]

[[openFile]]
name = "core/string.p2"
line = 126
active = 0

[[openFile]]
name = "test.p2"
line = 14
active = 1

[[openFile]]
name = "std/List.p2"
line = 0
active = 0
