[[general]]
currentProject = "C:/pvmoore/d/apps/PPL2/projects/dev/"
recentProjects = ["C:/pvmoore/d/apps/PPL2/projects/glfw/", "C:/pvmoore/d/apps/PPL2/projects/test/", "C:/pvmoore/d/apps/PPL2/projects/dev/"]
